name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  

jobs:
  compile:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: compile with Maven
      run: mvn compile
    - name: test with Maven
      run : mvn test

  security-checks:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Trivy Scan  #will scan for vulnarabilities
      run : trivy fs --format table --output trivy-report.html .
    - name: Git leaks scan  # willscan for any sensitive data that is passes in source code
      run : gitleaks detect .
    
      
   
